import type { Finding } from "../findings.js";
import type { ReadinessReport, ReportSection } from "./aggregate.js";

const BADGE: Record<ReadinessReport["overall"], string> = {
  READY: "🟢 READY",
  "NOT READY": "🔴 NOT READY",
  INCOMPLETE: "🟡 INCOMPLETE",
};

const SEV_LABEL: Record<Finding["severity"], string> = { fail: "❌ FAIL", warn: "⚠️ WARN", info: "ℹ️ INFO" };

function severityRank(f: Finding): number {
  return { fail: 0, warn: 1, info: 2 }[f.severity];
}

function findingBlock(f: Finding): string {
  const lines: string[] = [];
  lines.push(`##### ${SEV_LABEL[f.severity]} · \`${f.path}\``);
  lines.push("");
  lines.push(f.message);
  if (f.spec?.quote) {
    lines.push("");
    lines.push(`> **Spec (${f.spec.section}):** ${f.spec.quote}`);
    if (f.spec.url) lines.push(`>`, `> ${f.spec.url}`);
  } else if (f.spec?.section) {
    lines.push("");
    lines.push(`> **Spec:** ${f.spec.section}${f.spec.url ? ` — ${f.spec.url}` : ""}`);
  }
  if (f.fix) {
    lines.push("");
    lines.push(`**Fix:** ${f.fix}`);
  }
  lines.push("");
  return lines.join("\n");
}

function sectionBlock(section: ReportSection): string {
  const lines: string[] = [];
  const scoreText = section.score !== undefined ? ` — score ${section.score}/100` : "";
  lines.push(`### ${section.name}${scoreText}`);
  lines.push("");
  if (!section.present) {
    lines.push(`_Not run. Run \`acp-check ${section.command}\` to include this section._`);
    lines.push("");
    return lines.join("\n");
  }
  const c = section.counts ?? { fail: 0, warn: 0, info: 0 };
  lines.push(`**Target:** \`${section.target ?? "—"}\`  `);
  lines.push(`**Result:** ${c.fail} failing · ${c.warn} warnings · ${c.info} info`);
  lines.push("");
  const ordered = [...section.findings].sort((a, b) => severityRank(a) - severityRank(b));
  const fails = ordered.filter((f) => f.severity === "fail");
  const rest = ordered.filter((f) => f.severity !== "fail");
  if (fails.length === 0) {
    lines.push("✅ No conformance failures detected.");
    lines.push("");
  }
  for (const f of fails) lines.push(findingBlock(f));
  if (rest.length > 0) {
    lines.push("<details><summary>Warnings &amp; info</summary>");
    lines.push("");
    for (const f of rest) lines.push(findingBlock(f));
    lines.push("</details>");
    lines.push("");
  }
  return lines.join("\n");
}

/** Renders a client-shareable Markdown readiness report. */
export function renderMarkdownReport(report: ReadinessReport): string {
  const lines: string[] = [];
  lines.push(`# ACP Readiness Report`);
  lines.push("");
  lines.push(`## ${BADGE[report.overall]}`);
  lines.push("");
  const totals = report.sections.reduce(
    (acc, s) => {
      acc.fail += s.counts?.fail ?? 0;
      acc.warn += s.counts?.warn ?? 0;
      acc.info += s.counts?.info ?? 0;
      return acc;
    },
    { fail: 0, warn: 0, info: 0 }
  );
  lines.push(`**${totals.fail} conformance failures · ${totals.warn} warnings · ${totals.info} informational** across ${report.sections.filter((s) => s.present).length} section(s).`);
  lines.push("");
  lines.push("| Section | Status | Score | Fail | Warn | Info |");
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const s of report.sections) {
    const status = !s.present ? "— not run" : (s.counts?.fail ?? 0) > 0 ? "🔴 failing" : "🟢 passing";
    lines.push(
      `| ${s.name} | ${status} | ${s.score ?? "—"} | ${s.counts?.fail ?? "—"} | ${s.counts?.warn ?? "—"} | ${s.counts?.info ?? "—"} |`
    );
  }
  lines.push("");
  lines.push(
    `_Generated by acp-check ${report.toolVersion} against ACP spec release ${report.specRelease} (commit \`${report.specCommit.slice(0, 10)}\`) on ${report.generatedAt}._`
  );
  lines.push("");
  lines.push("---");
  lines.push("");
  for (const s of report.sections) lines.push(sectionBlock(s));
  lines.push("---");
  lines.push("");
  lines.push("### Notes");
  lines.push("");
  for (const n of report.notes) lines.push(`- ${n}`);
  lines.push("");
  return lines.join("\n");
}
